version: '3.1'
services:
  server:
    container_name: avni-server
    image: vind3v/avni-server:3.7
    ports:
      - "8021:8021"
    depends_on:
      - db
    networks:
      - avninet

  db:
    container_name: avni-db
    image: vind3v/avni-db:0.1
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=openchs
      - POSTGRES_DB=openchs
    networks:
      - avninet
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    container_name: avni-app
    image: vind3v/avni-app:3.8
    privileged: true
    network_mode: "host"
    ports:
      - "5037:5037"
    depends_on:
      - server

networks:
  avninet:
    driver: bridge

volumes:
  pgdata:

